apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: playground-app
spec:
  project: default
  source:
    repoURL: 'https://hub.docker.com/r/wil42/playground'
    targetRevision: HEAD
    path: k8s
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
