Vagrant.configure("2") do |config|
    config.vm.box = "debian/bookworm64"
    config.vm.synced_folder "./confs", "/vagrant"
  
    # Server
    config.vm.define "lfillouxS" , primary: true do |s|
      s.vm.hostname = "lfillouxS"
      s.vm.network "private_network", ip: "192.168.56.110"
      config.vm.provider "virtualbox" do |vb|
        vb.memory = 2048
        vb.cpus = 2
      end
      s.vm.provision "shell", path: "scripts/init.sh"
    end
  end