#!/bin/bash

CONFIG_FILE="./confs"

if [ -f "$CONFIG_FILE" ]; then
  echo "[INFO] Running commands from $CONFIG_FILE"
  bash "$CONFIG_FILE"
else
  echo "[ERROR] Config file not found at $CONFIG_FILE"
  exit 1
fi
