VAGRANTFILE_API_VERSION = "2"

Vagrant.configure("2") do |config|
    config.vm.box = "debian/bookworm64"
    config.vm.synced_folder "./confs", "/vagrant"
  
    # Server
    config.vm.define "aleferraS" , primary: true do |s|
      s.vm.hostname = "aleferraS"
      s.vm.network "private_network", ip: "192.168.56.110"
      config.vm.provider "virtualbox" do |vb|
        vb.memory = 2048
        vb.cpus = 2
      end
      s.vm.provision "shell", path: "scripts/init.sh", args: ["controller"]
    end
  
    # Worker
    config.vm.define "lfillouxSW" do |sw|
      sw.vm.hostname = "lfillouxSW"
      sw.vm.network "private_network", ip: "192.168.56.111"
      config.vm.provider "virtualbox" do |vb|
        vb.memory = 1024
        vb.cpus = 1
      end
      sw.vm.provision "shell", path: "scripts/init.sh", args: ["agent"]
    end
  end